name: 'Hello World!'
description: 'test'
inputs:
  text:
    description: 'input'
    required: true
    default: 'world'
outputs:
  time:
    description: 'time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    ${{inputs.text}}