name: Try to do some thing
on:
  # push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12, 14]
        os: [ ubuntu-latest]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - uses: x-cmd/action@main
        with:
          node-version: ${{ matrix.node }}
          shellcode: xws build ${{ matrix.os }}
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: x-cmd/action@main
        with:
          code: xws build linux

  macos: 
    runs-on: macos-11
    steps:
      - uses: x-cmd/action@main
        with:
          code: xws build macos
  cowsay:
    runs-on: ubuntu-latest
    env:
      ssh_key: '${{ secrets.ssh_key }}'
    steps:
      - uses: x-cmd/action@main
        with:
          code: git clone git@github.com:x-cmd/theme.git; ls theme
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Building
        uses: x-cmd/action@main
        env:
          entrypoint: exp/a.sh
  bot1:
    runs-on: ubuntu-latest
    steps:
      - name: install x-cmd && setup ssh publish
        run:  |
              eval "$(curl https://get.x-cmd.com/dev)" || true
              git clone git@gitee.com:x-cmd/x-cmd.git && cd x-cmd || exit
              x gh-action ssh "$SSH_PRIVATE_KEY" agent-zero 0@x-cmd.com || true
              xws pub0 || true
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  bot2:
    runs-on: ubuntu-latest
    steps:
      - name: install x-cmd && setup ssh publish
        uses: x-cmd/checkout
        with:
          ref: main
          sshkey: ${{ secrets.SSH_PRIVATE_KEY }}
          user/email: agent-zero/0@x-cmd.com
        run: xws pub0
