name: Publish-Cron-Test
on:
  # push:
  workflow_dispatch:

jobs:
  publisher:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: 
      git_email: 
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 10
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: main
        uses: x-cmd/action@main
        with:
          # code: x log +yanfa && x ws pub || true
          code: x ws art || true
          artifact_name: artifact
          artifact_path: ~/work/action/action/ws/.artifact
