name: Publish-Cron-Test
on:
  # push:
  workflow_dispatch:

jobs:
  publisher1:
    runs-on: ubuntu-latest

    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws test || true
  publisher2:
    runs-on: ubuntu-latest
    env: 
      ITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws test || true
  publisher3:
    runs-on: ubuntu-latest
    env:
      git_user: dongYaoPeople
      git_email: 18218042711@163.com
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws test || true
  publisher4:
    runs-on: ubuntu-latest
    env:
      ___X_CMD_CODESORUCE_REPO: dev
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws test || true
  publisher5:
    runs-on: ubuntu-latest
    env:
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws test || true
  publisher:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: 
      git_email: 
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 10
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 10
      - name: main
        uses: x-cmd/action@main
        with:
          # code: x log +yanfa && x ws pub || true
          code: x ws art || true
          artifact_name: artifact
          artifact_path: ~/work/action/action/ws/.artifact
